
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: ubuntu-latest
resources:
  repositories:
    - repository: sampleRepo
      type: github
      name: Joel981/sample
      ref: main
      endpoint: TempPrac
steps:
- template: demo.yml@sampleRepo
- parameters:
    name: priya
