[Yesterday 19:09] N, Joel Anto Williams (Cognizant)
stages:
- stage: Display
  jobs:
  - job: greetings
    steps:
      script: echo Hello world!
  - job: welcome
    steps:
      script: echo Welcome Everyone
- stage: End
  job: Over
  steps:
    script: echo Goodbye
